- name: add nodes to docker swarm
  docker_swarm:
    state: join
    advertise_addr: docker-worker-vm
    join_token: "{{ hostvars['token']['value'] }}"
    remote_addrs: vs-code1:2377

- name: add nodes to docker swarm
  docker_swarm:
    state: join
    advertise_addr: docker-worker-2-vm
    join_token: "{{ hostvars['token']['value'] }}"
    remote_addrs: vs-code1:2377