- name: add nodes to docker swarm
  docker_swarm:
    state: join
    advertise_addr: docker-worker-a
    join_token: "{{ hostvars['token']['value'] }}"
    remote_addrs: vs-code1:2377

- name: add nodes to docker swarm
  docker_swarm:
    state: join
    advertise_addr: docker-worker-b
    join_token: "{{ hostvars['token']['value'] }}"
    remote_addrs: vs-code1:2377